import{NextRequest,NextResponse}from'next/server';import{db}from'../../../../lib/db';import{SALON_ID}from'../../../../lib/config';import{availability}from'../../../../lib/availability';import{sendEmail}from'../../../../lib/email';
export async function POST(r:NextRequest){try{const b=await r.json();if(!b.serviceId||!b.startsAt||!b.name||!b.email||!b.phone)return NextResponse.json({error:'Please complete all required fields.'},{status:400});
const c=db();const{data:service,error:se}=await c.from('services').select('*').eq('id',b.serviceId).eq('salon_id',SALON_ID).single();if(se||!service)throw se||new Error('Service unavailable');
const date=b.localDate;const current=await availability(service.id,date);const slot=current.find((x:any)=>x.startsAt===b.startsAt);if(!slot)return NextResponse.json({error:'That appointment has just been taken. Please choose another time.'},{status:409});
let{data:client}=await c.from('clients').select('*').eq('salon_id',SALON_ID).ilike('email',b.email).maybeSingle();if(!client){const ins=await c.from('clients').insert({salon_id:SALON_ID,full_name:b.name,email:b.email,phone:b.phone}).select().single();if(ins.error)throw ins.error;client=ins.data}else{await c.from('clients').update({full_name:b.name,phone:b.phone}).eq('id',client.id)}
const ins=await c.from('appointments').insert({salon_id:SALON_ID,service_id:service.id,client_id:client.id,starts_at:slot.startsAt,ends_at:slot.endsAt}).select('*,salons:salon_id(*),clients:client_id(*),services:service_id(*)').single();
if(ins.error){if(ins.error.code==='23P01')return NextResponse.json({error:'That appointment was just booked by someone else. Please choose another time.'},{status:409});throw ins.error}
const a:any=ins.data,salon=a.salons;const when=new Intl.DateTimeFormat('en-AU',{timeZone:salon.timezone,weekday:'long',day:'numeric',month:'long',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(a.starts_at));const cancelUrl=new URL(`/cancel/${a.cancellation_token}`,r.nextUrl.origin).toString();
if(salon.client_confirmation_enabled)await sendEmail(client.email,`Booking confirmed — ${service.name}`,`<h2>You’re booked.</h2><p><b>${service.name}</b><br>${when}</p><p>${salon.name}</p><p><a href="${cancelUrl}">Cancel appointment</a></p>`);
if(salon.salon_notification_enabled)await sendEmail(salon.email,`New booking — ${b.name}`,`<h2>New booking</h2><p>${b.name}<br>${b.phone}<br>${b.email}</p><p><b>${service.name}</b><br>${when}</p>`);
return NextResponse.json({appointment:{id:a.id,startsAt:a.starts_at,endsAt:a.ends_at,cancellationToken:a.cancellation_token},service,salon:{name:salon.name,timezone:salon.timezone}})}catch(e:any){return NextResponse.json({error:e.message||'Booking failed'},{status:500})}}
