'use client';
import{useEffect,useState}from'react';
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export default function Setup(){const[step,setStep]=useState(0),[p,setP]=useState<any>({}),[h,setH]=useState<any[]>([]),[svc,setSvc]=useState<any[]>([]),[f,setF]=useState<any>({category:'Hair',name:'',description:'',duration_minutes:60,price_cents:0,buffer_before_minutes:0,buffer_after_minutes:0,active:true,sort_order:10});
useEffect(()=>{Promise.all([fetch('/api/admin/profile').then(r=>r.json()),fetch('/api/admin/availability').then(r=>r.json()),fetch('/api/admin/services').then(r=>r.json())]).then(([a,b,c])=>{setP(a.salon||{});setH(b.hours||[]);setSvc(c.services||[])})},[]);
async function saveProfile(){await fetch('/api/admin/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)})}
async function saveHours(){await fetch('/api/admin/availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hours:h})})}
async function addService(){if(!f.name)return;await fetch('/api/admin/services',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const j=await fetch('/api/admin/services').then(r=>r.json());setSvc(j.services||[]);setF({...f,name:'',description:'',duration_minutes:60,price_cents:0})}
async function next(){if(step===0)await saveProfile();if(step===1)await saveHours();setStep(Math.min(3,step+1))}
async function finish(){await saveProfile();await fetch('/api/admin/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({onboarding_complete:true})});location.href='/admin/calendar'}
return <main className="wizard"><div className="brand">SOLOSALON · SETUP</div><div className="steps">{[0,1,2,3].map(i=><div key={i} className={'stepbar '+(i<=step?'on':'')}/>)}</div><div className="card">
{step===0&&<><h2>Tell us about you</h2><p className="muted">These details appear on your booking page.</p><div className="grid two"><input placeholder="Business / salon name" value={p.name||''} onChange={e=>setP({...p,name:e.target.value})}/><input placeholder="Stylist name" value={p.stylist_name||''} onChange={e=>setP({...p,stylist_name:e.target.value})}/><input placeholder="Mobile" value={p.phone||''} onChange={e=>setP({...p,phone:e.target.value})}/><input placeholder="Email" value={p.email||''} onChange={e=>setP({...p,email:e.target.value})}/><input placeholder="Location e.g. Largs Bay, SA" value={p.location_text||''} onChange={e=>setP({...p,location_text:e.target.value})}/><input placeholder="Instagram URL" value={p.instagram_url||''} onChange={e=>setP({...p,instagram_url:e.target.value})}/><input placeholder="Facebook URL" value={p.facebook_url||''} onChange={e=>setP({...p,facebook_url:e.target.value})}/><input placeholder="TikTok URL" value={p.tiktok_url||''} onChange={e=>setP({...p,tiktok_url:e.target.value})}/></div><textarea style={{marginTop:10}} placeholder="Short booking message" value={p.booking_message||''} onChange={e=>setP({...p,booking_message:e.target.value})}/></>}
{step===1&&<><h2>Your working hours</h2><p className="muted">Anything outside these times cannot be booked online.</p>{h.map((x,i)=><div className="dayrow" key={x.weekday}><label className="toggleline daylabel"><input type="checkbox" checked={x.enabled} onChange={e=>{const n=[...h];n[i]={...x,enabled:e.target.checked};setH(n)}}/><b>{days[x.weekday]}</b></label><input type="time" disabled={!x.enabled} value={(x.start_time||'09:00').slice(0,5)} onChange={e=>{const n=[...h];n[i]={...x,start_time:e.target.value};setH(n)}}/><input type="time" disabled={!x.enabled} value={(x.end_time||'17:00').slice(0,5)} onChange={e=>{const n=[...h];n[i]={...x,end_time:e.target.value};setH(n)}}/></div>)}</>}
{step===2&&<><h2>Your services</h2><div className="grid two"><input placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><input placeholder="Service name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input type="number" placeholder="Price $" value={(f.price_cents||0)/100} onChange={e=>setF({...f,price_cents:Math.round(+e.target.value*100)})}/><input type="number" placeholder="Duration minutes" value={f.duration_minutes} onChange={e=>setF({...f,duration_minutes:+e.target.value})}/><input type="number" placeholder="Buffer after" value={f.buffer_after_minutes} onChange={e=>setF({...f,buffer_after_minutes:+e.target.value})}/></div><textarea style={{marginTop:10}} placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><button style={{marginTop:10}} onClick={addService}>Add service</button>{svc.map(s=><div className="between" style={{padding:'8px 0',borderBottom:'1px solid #eee'}} key={s.id}><span><b>{s.name}</b><br/><span className="muted">{s.duration_minutes} min</span></span><b>{s.price_cents===0?'Free':'$'+(s.price_cents/100).toFixed(0)}</b></div>)}</>}
{step===3&&<><h2>Ready to take bookings</h2><p className="muted">Your booking page now uses your profile, service menu and working hours.</p><div className="successnote">Profile ✓ &nbsp; Availability ✓ &nbsp; Services {svc.length?'✓':'—'}</div></>}
<div className="wizard-actions"><button className="ghost" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>Back</button>{step<3?<button onClick={next}>Continue</button>:<button onClick={finish}>Go to bookings</button>}</div></div></main>}