'use client';import{useEffect,useMemo,useState}from'react';
type S={id:string;category:string;name:string;description:string;duration_minutes:number;price_cents:number|null};
const money=(c:number|null)=>c==null?'POA':c===0?'Free':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(c/100);
const dur=(m:number)=>`${Math.floor(m/60)?Math.floor(m/60)+'h ':''}${m%60?m%60+'m':''}`.trim();
function dates(){let a=[];for(let i=0;i<14;i++){let d=new Date();d.setDate(d.getDate()+i);a.push(d)}return a}
export default function Book(){const[services,setServices]=useState<S[]>([]),[cat,setCat]=useState(''),[service,setService]=useState<S>(),[day,setDay]=useState<Date>(),[slots,setSlots]=useState<any[]>([]),[slot,setSlot]=useState<any>(),[form,setForm]=useState({name:'',email:'',phone:''}),[loading,setLoading]=useState(false),[done,setDone]=useState<any>(),[err,setErr]=useState('');const days=useMemo(dates,[]);
useEffect(()=>{fetch('/api/public/services').then(r=>r.json()).then(d=>{setServices(d.services||[]);if(d.services?.[0])setCat(d.services[0].category)}).catch(()=>setErr('Booking is temporarily unavailable.'))},[]);
const cats=[...new Set(services.map(s=>s.category))];
const filtered=services.filter(s=>s.category===cat);
async function chooseDay(d:Date){setDay(d);setSlot(undefined);setSlots([]);if(!service)return;let local=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');let r=await fetch(`/api/public/availability?service=${service.id}&date=${local}`),j=await r.json();setSlots(j.slots||[])}
async function book(){if(!service||!slot||!day)return;setLoading(true);setErr('');let local=day.getFullYear()+'-'+String(day.getMonth()+1).padStart(2,'0')+'-'+String(day.getDate()).padStart(2,'0');let r=await fetch('/api/public/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,serviceId:service.id,startsAt:slot.startsAt,localDate:local})}),j=await r.json();setLoading(false);if(r.ok)setDone(j);else{setErr(j.error||'Could not book.');if(r.status===409)chooseDay(day)}}
if(done)return <main className="shell"><div className="brand">OPENBOOK</div><div className="card success" style={{marginTop:50}}><div className="check">✓</div><h1>You’re booked.</h1><p><b>{done.service.name}</b></p><p className="muted">Your appointment is confirmed. No account needed.</p><button onClick={()=>location.reload()}>Book another</button></div></main>;
return <main className="shell"><div className="brand">OPENBOOK · DEMO SALON</div><h1>Book your appointment</h1><p className="muted">Pick a service. See real availability. Confirm in under a minute.</p>{err&&<div className="notice">{err}</div>}<div className="card">
<div className="step">1 · SERVICE</div><div className="categorybar">{cats.map(c=><button className={'pill '+(cat===c?'on':'')} onClick={()=>{setCat(c);setService(undefined);setDay(undefined)}} key={c}>{c}</button>)}</div><div className="grid services" style={{marginTop:10}}>{filtered.map(s=><button className={'service '+(service?.id===s.id?'on':'')} key={s.id} onClick={()=>{setService(s);setDay(undefined);setSlot(undefined)}}><div><b>{s.name}</b><p className="muted" style={{margin:'6px 0'}}>{s.description}</p><span>{dur(s.duration_minutes)} · <b>{money(s.price_cents)}</b></span></div></button>)}</div>
{service&&<><div className="step">2 · DATE</div><div className="date-row">{days.map(d=>{let same=day?.toDateString()===d.toDateString();return <button className={'date '+(same?'on':'')} onClick={()=>chooseDay(d)} key={d.toISOString()}><small>{d.toLocaleDateString('en-AU',{weekday:'short'}).toUpperCase()}</small><b>{d.getDate()}</b></button>})}</div></>}
{day&&<><div className="step">3 · TIME</div><div className="grid slots">{slots.length?slots.slice(0,20).map(x=><button key={x.startsAt} className={'slot '+(slot?.startsAt===x.startsAt?'on':'')} onClick={()=>setSlot(x)}>{new Date(x.startsAt).toLocaleTimeString('en-AU',{hour:'numeric',minute:'2-digit'})}</button>):<p className="muted">No times this day. Choose another date.</p>}</div></>}
{slot&&service&&<><div className="step">4 · DETAILS</div><div className="summary"><div><b>{service.name}</b><div className="muted">{day?.toLocaleDateString('en-AU',{weekday:'long',day:'numeric',month:'long'})} · {new Date(slot.startsAt).toLocaleTimeString('en-AU',{hour:'numeric',minute:'2-digit'})}</div></div><b>{money(service.price_cents)}</b></div><div className="grid two" style={{marginTop:12}}><input placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Mobile" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><input style={{marginTop:10}} type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button style={{width:'100%',marginTop:12}} disabled={loading||!form.name||!form.email||!form.phone} onClick={book}>{loading?'Booking…':'Confirm appointment'}</button></>}
</div><p className="muted" style={{fontSize:12,textAlign:'center'}}>No account required · Your details are only used for your appointment</p></main>}