'use client';import{useEffect,useMemo,useState}from'react';
type S={id:string;category:string;name:string;description:string;duration_minutes:number;price_cents:number|null};
const money=(c:number|null)=>c==null?'POA':c===0?'Free':'$'+(c/100).toFixed(0);
function dates(){return Array.from({length:21},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return d})}
export default function Book(){
 const[services,setServices]=useState<S[]>([]),[salon,setSalon]=useState<any>(),[cat,setCat]=useState(''),[service,setService]=useState<S>(),[day,setDay]=useState<Date>(),[slots,setSlots]=useState<any[]>([]),[slot,setSlot]=useState<any>(),[form,setForm]=useState({name:'',email:'',phone:''}),[done,setDone]=useState(false),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const days=useMemo(dates,[]);
 useEffect(()=>{fetch('/api/public/services').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setServices(d.services||[]);setSalon(d.salon);if(d.services?.[0])setCat(d.services[0].category)}).catch(e=>setErr(e.message||'Booking is unavailable.'))},[]);
 const cats=[...new Set(services.map(s=>s.category))],filtered=services.filter(s=>s.category===cat);
 async function chooseDay(d:Date){setDay(d);setSlot(undefined);setSlots([]);setErr('');const local=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');const r=await fetch(`/api/public/availability?service=${service?.id}&date=${local}`),j=await r.json();if(!r.ok)setErr(j.error||'Could not load times.');setSlots(j.slots||[])}
 async function book(){if(!service||!slot||!form.name||!form.email||!form.phone)return;setBusy(true);setErr('');const r=await fetch('/api/public/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,serviceId:service.id,startsAt:slot.startsAt})});const j=await r.json();setBusy(false);if(r.ok)setDone(true);else setErr(j.error||'Could not complete booking.')}
 if(done)return <main className="shell"><div className="card success"><div className="check">✓</div><h1>You’re booked.</h1><p className="muted">Your appointment has been added successfully.</p><button onClick={()=>location.reload()}>Book another</button></div></main>;
 return <main className="shell"><div className="booking-head"><div className="brand">{salon?.name?.toUpperCase()||'SOLOSALON'}</div><h1>Book your appointment</h1><p className="muted">{salon?.booking_message||'Choose a service and book a time that suits you.'}</p></div>{err&&<div className="notice">{err}</div>}<div className="card">
 <div className="step">1 · SERVICE</div><div className="categorybar">{cats.map(c=><button key={c} className={'pill '+(cat===c?'on':'')} onClick={()=>{setCat(c);setService(undefined);setDay(undefined);setSlot(undefined)}}>{c}</button>)}</div>
 <div className="grid services">{filtered.map(s=><button key={s.id} className={'service '+(service?.id===s.id?'on':'')} onClick={()=>{setService(s);setDay(undefined);setSlot(undefined)}}><b>{s.name}</b><p className="muted">{s.description}</p><span>{s.duration_minutes} min · <b>{money(s.price_cents)}</b></span></button>)}</div>
 {service&&<><div className="step">2 · DATE</div><div className="date-row">{days.map(d=><button key={d.toISOString()} className={'date '+(day?.toDateString()===d.toDateString()?'on':'')} onClick={()=>chooseDay(d)}><small>{d.toLocaleDateString('en-AU',{weekday:'short'})}</small><b>{d.getDate()}</b></button>)}</div></>}
 {day&&<><div className="step">3 · TIME</div><div className="grid slots">{slots.length?slots.map(x=><button key={x.startsAt} className={'slot '+(slot?.startsAt===x.startsAt?'on':'')} onClick={()=>setSlot(x)}>{new Date(x.startsAt).toLocaleTimeString('en-AU',{hour:'numeric',minute:'2-digit'})}</button>):<p className="muted">No times available this day.</p>}</div></>}
 {slot&&<><div className="step">4 · DETAILS</div><div className="grid two"><input placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Mobile" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><input style={{marginTop:10}} placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button style={{width:'100%',marginTop:12}} disabled={busy||!form.name||!form.phone||!form.email} onClick={book}>{busy?'Booking…':'Confirm appointment'}</button></>}
 </div></main>
}