'use client';
import{useEffect,useMemo,useState}from'react';
type S={id:string;category:string;name:string;description:string;duration_minutes:number;price_cents:number|null};
const money=(c:number|null)=>c==null?'POA':c===0?'Free':'$'+(c/100).toFixed(0);
function dates(){return Array.from({length:21},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return d})}
const goals=['Blonder & brighter','Lived-in blonde','Brunette / dimensional','Cover greys','Refresh my colour','Big change','Extensions','Cut / styling'];
const hair=['Natural / mostly natural','Previously coloured','Blonde','Dark / brunette','Not sure'];
const priorities=['Maximum transformation','Maintenance-friendly','Just needs refreshing','You decide — I’m not sure'];
export default function Book(){
 const[services,setServices]=useState<S[]>([]),[salon,setSalon]=useState<any>(),[mode,setMode]=useState<'start'|'help'|'again'|'browse'>('start'),[guide,setGuide]=useState(0),[goal,setGoal]=useState(''),[base,setBase]=useState(''),[priority,setPriority]=useState(''),[cat,setCat]=useState(''),[service,setService]=useState<S>(),[day,setDay]=useState<Date>(),[slots,setSlots]=useState<any[]>([]),[slot,setSlot]=useState<any>(),[form,setForm]=useState({name:'',email:'',phone:''}),[returning,setReturning]=useState({surname:'',phone:''}),[matched,setMatched]=useState(false),[done,setDone]=useState(false),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const days=useMemo(dates,[]);
 useEffect(()=>{fetch('/api/public/services').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setServices(d.services||[]);setSalon(d.salon);if(d.services?.[0])setCat(d.services[0].category)}).catch(e=>setErr(e.message||'Booking is unavailable.'))},[]);
 const cats=[...new Set(services.map(s=>s.category))],filtered=services.filter(s=>s.category===cat);
 function resetBooking(){setDay(undefined);setSlot(undefined);setSlots([]);setErr('')}
 async function chooseDay(d:Date){setDay(d);setSlot(undefined);setSlots([]);setErr('');const local=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');const r=await fetch(`/api/public/availability?service=${service?.id}&date=${local}`),j=await r.json();if(!r.ok)setErr(j.error||'Could not load times.');setSlots(j.slots||[])}
 async function book(){if(!service||!slot||!form.name||!form.email||!form.phone)return;setBusy(true);setErr('');const r=await fetch('/api/public/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,serviceId:service.id,startsAt:slot.startsAt})});const j=await r.json();setBusy(false);if(r.ok)setDone(true);else setErr(j.error||'Could not complete booking.')}
 function recommend(){const words=(goal+' '+priority).toLowerCase();let found=services.find(s=>words.split(' ').some(w=>w.length>5&&s.name.toLowerCase().includes(w)));if(!found)found=services.find(s=>s.category.toLowerCase().includes(goal.split(' ')[0].toLowerCase()));if(!found)found=services[0];setService(found);resetBooking();setGuide(3)}
 function pick(v:string){if(guide===0){setGoal(v);setGuide(1)}else if(guide===1){setBase(v);setGuide(2)}else{setPriority(v);setTimeout(recommend,0)}}
 if(done)return <main className="shell"><div className="card success"><div className="check">✓</div><h1>You’re booked.</h1><p className="muted">Your appointment has been added successfully.</p><button onClick={()=>location.reload()}>Book another</button></div></main>;
 const availability=<>{service&&<><div className="step">DATE</div><div className="date-row">{days.map(d=><button key={d.toISOString()} className={'date '+(day?.toDateString()===d.toDateString()?'on':'')} onClick={()=>chooseDay(d)}><small>{d.toLocaleDateString('en-AU',{weekday:'short'})}</small><b>{d.getDate()}</b></button>)}</div></>}{day&&<><div className="step">TIME</div><div className="grid slots">{slots.length?slots.map(x=><button key={x.startsAt} className={'slot '+(slot?.startsAt===x.startsAt?'on':'')} onClick={()=>setSlot(x)}>{new Date(x.startsAt).toLocaleTimeString('en-AU',{hour:'numeric',minute:'2-digit'})}</button>):<p className="muted">No times available this day.</p>}</div></>}{slot&&<><div className="step">YOUR DETAILS</div><div className="grid two"><input placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Mobile" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><input style={{marginTop:10}} placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button style={{width:'100%',marginTop:12}} disabled={busy||!form.name||!form.phone||!form.email} onClick={book}>{busy?'Booking…':'Confirm appointment'}</button></>}</>;
 return <main className="shell"><div className="booking-head"><div className="brand">{salon?.name?.toUpperCase()||'MISS PIA HAIR'}</div><h1>{mode==='start'?'Book your way.':'Book your appointment'}</h1><p className="muted">{mode==='start'?"Tell us how you'd like to start — we'll take care of the complicated bits.":salon?.booking_message||'Choose a service and book a time that suits you.'}</p></div>{err&&<div className="notice">{err}</div>}
 {mode==='start'&&<div className="booking-entry"><button className="entry-card featured" onClick={()=>{setMode('help');setGuide(0)}}><span className="entry-icon">✨</span><span><b>Help me choose</b><small>Not sure what to book? We’ll work it out together.</small></span><i>→</i></button><button className="entry-card" onClick={()=>setMode('again')}><span className="entry-icon">↻</span><span><b>Book again</b><small>Loved your last appointment? Rebook it in a few taps.</small></span><i>→</i></button><button className="entry-card" onClick={()=>setMode('browse')}><span className="entry-icon">⌕</span><span><b>I know what I want</b><small>Browse our full service menu.</small></span><i>→</i></button></div>}
 {mode==='help'&&<div className="card"><button className="text-back" onClick={()=>guide?setGuide(guide-1):setMode('start')}>← Back</button>{guide<3&&<><div className="guide-progress"><span className={guide>=0?'on':''}/><span className={guide>=1?'on':''}/><span className={guide>=2?'on':''}/></div><div className="step">HELP ME CHOOSE · {guide+1} OF 3</div><h2 className="guide-title">{guide===0?'What are you looking to achieve?':guide===1?'What are we starting with?':'What matters most today?'}</h2><div className="guide-grid">{(guide===0?goals:guide===1?hair:priorities).map(x=><button key={x} onClick={()=>pick(x)}>{x}<i>→</i></button>)}</div></>}{guide===3&&<><div className="step">YOUR BOOKING</div><h2 className="guide-title">We think this is your perfect booking.</h2><div className="recommend-box"><small>RECOMMENDED FOR YOU</small><h3>{service?.name||goal}</h3><p className="muted">Based on wanting <b>{goal.toLowerCase()}</b>, starting with <b>{base.toLowerCase()}</b>, with a focus on <b>{priority.toLowerCase()}</b>.</p>{service&&<div className="ticket-pop"><span>Added to your ticket</span><b>{service.name}</b><small>{service.duration_minutes} min · {money(service.price_cents)}</small></div>}<p className="muted tiny">We’ve translated your answers into the salon services needed behind the scenes.</p></div>{availability}</>}</div>}
 {mode==='again'&&<div className="card"><button className="text-back" onClick={()=>{setMode('start');setMatched(false)}}>← Back</button><div className="step">BOOK AGAIN</div>{!matched?<><h2 className="guide-title">Let’s find you.</h2><p className="muted">No password. Enter the details you used when booking with us.</p><div className="grid two"><input placeholder="Surname" value={returning.surname} onChange={e=>setReturning({...returning,surname:e.target.value})}/><input placeholder="Mobile number" inputMode="tel" value={returning.phone} onChange={e=>setReturning({...returning,phone:e.target.value})}/></div><button className="wide" disabled={!returning.surname||!returning.phone} onClick={()=>setMatched(true)}>Find me →</button><p className="privacy-note">For this prototype we don’t reveal any previous booking history.</p></>:<><h2 className="guide-title">Welcome back 👋</h2><p className="muted">We found your details. Your previous services stay private — we’ll only use them to build your next booking.</p><button className="entry-card featured inline-entry" onClick={()=>{setService(services[0]);resetBooking()}}><span><b>↻ Book my usual</b><small>Build my booking from my usual appointment.</small></span><i>→</i></button>{service&&<><div className="ticket-pop"><span>Your ticket is ready</span><b>{service.name}</b><small>{service.duration_minutes} min · {money(service.price_cents)}</small></div>{availability}</>}<button className="ghost wide" onClick={()=>setMode('browse')}>Choose something different</button></>}</div>}
 {mode==='browse'&&<div className="card"><button className="text-back" onClick={()=>setMode('start')}>← Back</button><div className="step">SERVICE</div><div className="categorybar">{cats.map(c=><button key={c} className={'pill '+(cat===c?'on':'')} onClick={()=>{setCat(c);setService(undefined);resetBooking()}}>{c}</button>)}</div><div className="grid services">{filtered.map(s=><button key={s.id} className={'service '+(service?.id===s.id?'on':'')} onClick={()=>{setService(s);resetBooking()}}><b>{s.name}</b><p className="muted">{s.description}</p><span>{s.duration_minutes} min · <b>{money(s.price_cents)}</b></span></button>)}</div>{availability}</div>}
 </main>
}
